source "http://rubygems.org"
source "http://gemcutter.org"

gem "sinatra"
gem "sinatra-content-for"
gem "sinatra-reloader"
gem "haml"
gem "sass"
gem "dm-core"
gem "dm-validations"
gem "dm-migrations"
gem "dm-timestamps"
gem "dm-serializer"